// Builds the standalone dedicated-server binaries (npm run dist:server) with Bun: one executable per OS,
// each with the web build (dist/) embedded, so the binary alone serves the game page + co-op traffic.
// Usage: node scripts/build-server.mjs [target...]   (targets: windows-x64 macos-x64 macos-arm64 linux-x64)
import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, statSync, writeFileSync, unlinkSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import os from 'node:os';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const DIST = path.join(ROOT, 'dist');
const OUT = path.join(ROOT, 'release', 'server');
const BUN = process.env.BUN ?? (existsSync(path.join(os.homedir(), '.bun/bin/bun')) ? path.join(os.homedir(), '.bun/bin/bun') : 'bun');
const TARGETS = { 'windows-x64': 'bun-windows-x64', 'macos-x64': 'bun-darwin-x64', 'macos-arm64': 'bun-darwin-arm64', 'linux-x64': 'bun-linux-x64' };
const want = process.argv.slice(2).length ? process.argv.slice(2) : Object.keys(TARGETS);

if (!existsSync(path.join(DIST, 'index.html'))) { console.error('dist/ is missing: run `npm run build` first.'); process.exit(1); }
const files = [];
const walk = (d) => { for (const n of readdirSync(d)) { const p = path.join(d, n); if (statSync(p).isDirectory()) walk(p); else if (n !== '.DS_Store') files.push(p); } };
walk(DIST);

// a generated entry that imports every dist/ file as an embedded asset (Bun keeps them inside the executable)
mkdirSync(OUT, { recursive: true });
const entry = path.join(OUT, '.entry.ts');
const rel = (p) => path.relative(OUT, p).split(path.sep).join('/');
writeFileSync(entry, [
  '// generated by scripts/build-server.mjs: do not edit',
  `import { cli } from '${rel(path.join(ROOT, 'src/server/dedicated'))}';`,
  ...files.map((f, i) => `import f${i} from '${rel(f)}' with { type: 'file' };`),
  'declare const Bun: any;',
  `const FILES: Record<string, string> = { ${files.map((f, i) => `${JSON.stringify('/' + path.relative(DIST, f).split(path.sep).join('/'))}: f${i}`).join(', ')} };`,
  'void cli(async (p) => { const f = FILES[p]; return f ? new Uint8Array(await Bun.file(f).arrayBuffer()) : null; });',
].join('\n'));

try {
  for (const name of want) {
    const target = TARGETS[name];
    if (!target) { console.error(`unknown target ${name}`); process.exit(1); }
    const outfile = path.join(OUT, `towerbreach-server-${name}${name.startsWith('windows') ? '.exe' : ''}`);
    console.log(`building ${path.relative(ROOT, outfile)} (${target}, ${files.length} web files embedded)`);
    execFileSync(BUN, ['build', '--compile', '--minify', `--target=${target}`, entry, '--outfile', outfile], { stdio: 'inherit', cwd: ROOT });
  }
} finally { unlinkSync(entry); }
